name: triease_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.33
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.7+3 # Keep this version
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/Let me down.mp3
    - assets/trieasenew.png
    - assets/logonew.png
    - assets/google.png
    